---
   - name: Installing MySQL
     ansible.builtin.apt:
        name: "{{ item }}"
        state: present
        update_cache: true
     loop: "{{ package_name }}"
   
   - name: ensure MySQL always starts
     ansible.builtin.service:
      name: mysql
      state: started
      enabled: yes
    
   - name: Set the root password
     community.mysql.mysql_user:
      login_host: 'localhost'
      login_user: 'root'
      login_password: ''
      name: 'root'
      password: "{{ mysql_root_password }}"
      state: present
      login_unix_socket: /var/run/mysqld/mysqld.sock

   - name: Creating database for Wordpress
     ansible.builtin.mysql_db:
      name: "{{ mysql_db }}"
      state: present
      login_user: root
      login_password: "{{ mysql_root_password }}"

   - name: Create MySQL user for Wordpress
     ansible.builtin.mysql_user:
      name: "{{ mysql_user }}"
      password: "{{ mysql_password }}"
      state: present
      priv: "{{ mysql_db }}.*:ALL"
      login_user: root
      login_password: "{{ mysql_root_password }}"